# Production stage: serve built assets with nginx
FROM nginx:stable-alpine

# Download release
RUN wget https://github.com/GraphiteEditor/Graphite/releases/download/latest-stable/graphite-self-hosted-build.zip \
    && unzip graphite-self-hosted-build.zip \
    && rm graphite-self-hosted-build.zip \
    && mv graphite*/* /usr/share/nginx/html \
    && rm -r graphite*

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

